### ISSUE TITLE
About image input format 

### ISSUE THREAD

**Issue by lkccu** [IlvaHou55/canny_edge_detector_3D#1]
Hi, author@IlvaHou55, I have encountered some troubles when running your code.When I input a 128*128*128 3D CT-data, there is no output and the program halted when executing **tracker1 = slicer_3D.Slicer3D(ax1, img_edges)**. I wonder there is something wrong with the input format. I am running the code under Win10, python 3.9. Could you please help me with it?

Thank you in advance

**Comment by IlvaHou55** [comment]
Hello, that is unfortunate. Would you be able to share the data? That makes it a lot easier to see where the problems come from.

**Comment by lkccu** [comment]
> Hello, that is unfortunate. Would you be able to share the data? That makes it a lot easier to see where the problems come from.

No...I found that it nothing about dataset. I made use of the MRI image you refered AND encountered the same problem. I doubted whether the code available in Windows.

**Comment by IlvaHou55** [comment]
I rerun my code and did not find any issues. Let's check some boxes:
- Have you downloaded canny_edge_detector_3D.py and slicer_3D.py?
- Have you saved them in the site-packages folder of your Python folder?
- Did you start your script with: `import canny_edge_detector_3D` and `import slicer_3D`? 

Have a look at the notebook that I made, to see an example of how to use the code.

**Comment by lkccu** [comment]
Thanks a lot. I have downloaded your code and run **Canny_Edge_Detection_3D_Example_Notebook.ipynb** in jupyter notebook and replace the image path of your example iamge MRI_4.nii. I didn't saved **canny_edge_detector_3D** and ** slicer_3D** in the site-packages folder but I am sure they are in the same folder. But they did somehow not work.

**Comment by lkccu** [comment]
Hi author, would you please tell me about your python version and other version numbers?

**Comment by IlvaHou55** [comment]
Hello, I use Python 3.7.9, Windows 10, NumPy 1.19.3, Matplotlib 3.5.1, scipy 1.7.3 and medpy 0.3.0

**Comment by lkccu** [comment]
Oh thx! I changed the interpreter and somehow it works! Idk why it happens but it did work well now! Thank you for your time.
