### ISSUE TITLE
work badly on CT data

### ISSUE THREAD

**Issue by lkccu** [IlvaHou55/canny_edge_detector_3D#2]
Hi author @IlvaHou55, it's me again. I encountered another problem when I run on my 3d-CT data. It outputs a black figure as shown. I tried to tune the hyper-parameters but it did not work. Could you help with it ? Sorry to disturb. Your code means a lot to my work and thank you very very very much.
![7ec45524961aa43f2df105cb251d32c](https://user-images.githubusercontent.com/91356315/200794142-935faab8-2880-4b96-8cb4-bb0eb05fef24.jpg)

**Comment by IlvaHou55** [comment]
Hi @lkccu, I think I will only be able to help if you will share your data with me. This does not have to be here out in the open, but you can also contact me privately for this (93598891+IlvaHou55@users.noreply.github.com).

**Comment by lkccu** [comment]
Thank you! I have sent it to you just now.

**Comment by lkccu** [comment]
Hi author @IlvaHou55 ,have you figured it out or could you please tell me about the concrete meaning of these parameters so that I can tried my best in it? Thank you!

**Comment by IlvaHou55** [comment]
@lkccu I have not seen any mail with the data, unfortunately. Maybe try to send it to this email instead: canny_edge_detector_3d@noreply.github.com

**Comment by lkccu** [comment]
I have sent it to this mail.It somehow failed when sending to previous mail.Hope it success this time.Thank you for your time.

**Comment by IlvaHou55** [comment]
I am sorry, but I still did not receive anything.
