### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwinsnes** [IlvaHou55/canny_edge_detector_3D#3]
Hello!

I'm looking into performing Canny Edge detection in 3D and your class looks perfect for the purpose.

However, there is no indication of license in the repo. 
The README note suggests that it is open to use but I would like to know for sure. 

So under what license is this repo? And could you please add a LICENSE file to indicate it?

**Comment by IlvaHou55** [comment]
Hello @cwinsnes,

Nice to hear that you want to make use of this function. By the time I posted this, I was not really thinking about licensing. More that I was doing some work that could be helpful for others too. I've added a license now. Still open source, but licensed under Apache 2.0. 

Best,
Ilva
